name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda 1×/dia às 00:00 UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: Platane/snk@v3
        with:
          github_user_name: AspMartins999
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update contribution snake"
          add: "*.svg"
          branch: output
          push: true
